
#ifndef PXHASH_H
#include "pxHash.h"
#endif

#ifndef PX_LIMITS_H
#include <limits.h>
#define PX_LIMITS_H
#endif


static const unsigned pxHash_random[]; // initialized below

#define PXHASH_ROT_LEFT 5
#define PXHASH_ROT_RIGHT (sizeof(pxHashValue) * CHAR_BIT - PXHASH_ROT_LEFT)

void pxHashVoid(pxHashValue *pHash, const void *p, size_t length)
{
    for(const unsigned char *pc = (const unsigned char *)p;
        length; ++pc, --length)
    {
        *pHash ^= pxHash_random[*pc];

        // rotate left 5 bits
        *pHash =
            (*pHash << PXHASH_ROT_LEFT) |
            (((unsigned)*pHash) >> PXHASH_ROT_RIGHT);
    }
}

void pxHashString(pxHashValue *pHash, const void *p)
{
    for(const unsigned char *pc = (const unsigned char *)p; *pc != '\0'; ++pc)
    {
        *pHash ^= pxHash_random[*pc];

        // rotate left 5 bits
        *pHash =
            (*pHash << PXHASH_ROT_LEFT) |
            (((unsigned)*pHash) >> PXHASH_ROT_RIGHT);
    }
}

void pxHashInt(pxHashValue *pHash, const void *p)
{
    pxHashVoid(pHash, p, sizeof(int));
}


// generated by the program below
static const unsigned pxHash_random[] =
{
    0x379abbb2,
    0x55893d4b,
    0xf20b349b,
    0xd1fb870a,
    0x7ac5c5e6,
    0x208b0d2e,
    0xd4fe02e2,
    0x27abf450,
    0xbdd72833,
    0x854bd13f,
    0xdd6412fa,
    0x04542247,
    0x44b1f091,
    0x4241b43e,
    0xd515ae91,
    0xcf1340c3,
    0xdf60d3cc,
    0x3efeff1f,
    0x0fefd01e,
    0xebb57c98,
    0xf2a50249,
    0xb6efd412,
    0xf7d01a4a,
    0x0cd62ce5,
    0x6d84e85e,
    0x3ef13c45,
    0x8d1bbf74,
    0x713116a4,
    0xa1c1f8ac,
    0xa542c292,
    0x02bd7a80,
    0x87a8efa7,
    0x8354cc22,
    0xaae12e88,
    0xa8e71ff3,
    0xb4a08d0c,
    0x951ea9ad,
    0x0a67d873,
    0xeecec91d,
    0x6ee4065d,
    0x416b666a,
    0x2a72f145,
    0x36d2537c,
    0x810b8c69,
    0xd24d7089,
    0x4af8a27e,
    0x527e0a9e,
    0x785185e0,
    0xf59f4724,
    0x14d48e28,
    0x13101baf,
    0x8a1bd7da,
    0xc42a7b57,
    0xbe820354,
    0x9d43c614,
    0x095d72ea,
    0x31c4c7e7,
    0x5dd460af,
    0x2b25a0fd,
    0x52584a50,
    0xde37db96,
    0x953d43d9,
    0x2fdf05fa,
    0x73bcab75,
    0x6f43e86c,
    0x45677a08,
    0x20486d1d,
    0x5addc4c9,
    0x6d642d3a,
    0x35027f00,
    0x3b066aa7,
    0xc13fcb83,
    0xa29334c9,
    0x55f50eb1,
    0x85f0d204,
    0x8bb101b4,
    0x6f04fbd6,
    0xa796e97d,
    0xcea4f414,
    0x84b31997,
    0x6e9c17d3,
    0x4fe83a68,
    0x5c9db8e7,
    0xdb991946,
    0xacf1139c,
    0xe9e0316c,
    0x665caa74,
    0xebb663d0,
    0xce573360,
    0xd9d07262,
    0xc8561c71,
    0xb0417969,
    0x2c8e78fd,
    0xcc669a8b,
    0xb8f6aa27,
    0xbfcfff82,
    0xbe00f651,
    0x3ff9e351,
    0xcb529738,
    0xc9113801,
    0x6b10735a,
    0x81a2e970,
    0xc60395bf,
    0x9e3e297c,
    0xcde37697,
    0xaeb87326,
    0x8ab9a424,
    0x21253271,
    0xc24cdd08,
    0x0ef60ca8,
    0xe1c4d194,
    0x909b4d2f,
    0x363fc5de,
    0xc3f74819,
    0xaef0cd07,
    0xcf3c8705,
    0xed046253,
    0xe464c0d6,
    0xbb925e5a,
    0x03354c12,
    0x77f3a223,
    0xdc7f064e,
    0x94b7d9ec,
    0x81515356,
    0xb20f86a6,
    0x688940fc,
    0xe51d78a3,
    0x43c6a1dc,
    0x41e607a9,
    0x2267a47a,
    0x6f0eb079,
    0x98d5f74e,
    0x3c443977,
    0x5d29c1ee,
    0x862a4d07,
    0x1e3b7556,
    0x4d93e6e2,
    0x241dcc80,
    0x5017ba4f,
    0x16ada6d3,
    0x1eb1a8e5,
    0x75b75884,
    0x465c6639,
    0x01f87e7f,
    0x252f0b97,
    0xe1475ea9,
    0xcd658f4c,
    0x67a6daeb,
    0x37c730de,
    0xd882c3f6,
    0x8e98d5ac,
    0x991c75ee,
    0xdab462be,
    0x2c909938,
    0x98b05618,
    0x5f207ccf,
    0x12d81040,
    0xe7b53488,
    0x118160ca,
    0x1bd29c3c,
    0xa37bec39,
    0xfe333659,
    0x9f8b9ce3,
    0x06c75029,
    0xea861f2f,
    0xba9226b2,
    0x03b7c086,
    0x42edc1b6,
    0x23aaff39,
    0x4e17d35e,
    0x9e2df38e,
    0xfa7dfcc2,
    0x8a5fa900,
    0x8f2b4290,
    0x1562613b,
    0x492b0835,
    0xadc64e30,
    0x47afc805,
    0xb5fc1483,
    0x9592bc33,
    0x32fc5b7e,
    0x5cb6376d,
    0x46af852e,
    0x5405a529,
    0x576cb36a,
    0x6593df8d,
    0x5b70dc79,
    0x40705bc8,
    0x8fa6c79b,
    0x6aa7f5d1,
    0x32fd34e6,
    0xfec0b7c5,
    0x740f8299,
    0x634b5f3a,
    0x58bd0e1c,
    0xe576b96b,
    0x803d9f30,
    0x0f364444,
    0x3d4c49ba,
    0xa38d761c,
    0x9b74eaf9,
    0xac079091,
    0xb8b0ab68,
    0x89e4e088,
    0x17a0db38,
    0xdeecbc8f,
    0x72235fcb,
    0x68f4581a,
    0xce596355,
    0xf09fd916,
    0xda9a1a8c,
    0xb9cad5c2,
    0x7dadc8f5,
    0x7794092c,
    0xdd6fedf9,
    0x87784588,
    0x28ef219e,
    0x182d63b9,
    0x6e26937b,
    0x20591908,
    0x2777d809,
    0x1871fd91,
    0x6eaed69a,
    0xbf463ae4,
    0xa1f8cadf,
    0xf1592735,
    0xcb6915e2,
    0xebd7bbca,
    0x1a11f3ec,
    0x55a5832e,
    0xee492a00,
    0x21bdc322,
    0xdc84800d,
    0x2ba14bcd,
    0xfbbb260b,
    0xfa31614f,
    0xdb0d01f2,
    0x760cb257,
    0xe248185b,
    0x2dff6c8a,
    0x8c96ea09,
    0x9d52110d,
    0x109623c0,
    0x65fba0e3,
    0x5a1f9461,
    0x4ae12821,
    0x249d644f,
    0xa3bc65f4,
    0x2561ed30,
    0xe9136bba,
    0xb5d73bb3,
    0xe8e0be15,
    0x5316f9f7,
    0xab488c7f,
    0xf2b37d32,
    0x7b79690a,

};

#ifdef PX_NEVER

#ifndef PX_STDIO_H
#include <stdio.h>
#define PX_STDIO_H
#endif

#ifndef PX_STDLIB_H
#include <stdlib.h>
#define PX_STDLIB_H
#endif


typedef union
{
    unsigned char ub[4];
    unsigned u;
} unsignedBytes;

int main(void)
{
    if (sizeof(unsigned) != 4)
    {
        fprintf(stderr, "sizeof(unsigned) != 4\n");
        exit(1);
    }

    const int nBytes = 256; // the number of distinct bytes
    unsignedBytes b[nBytes];

    // initialize each int's bytes with all the values
    for(int i = 0; i < nBytes; ++i)
    {
        b[i].ub[0] = i;
        b[i].ub[1] = i;
        b[i].ub[2] = i;
        b[i].ub[3] = i;
    }

    // scramble the values well
    srandom(0x20130422);
    unsigned char *pc = (unsigned char *)b;
    for(int i = 0; i < 1000000; ++i)
    {
        long ia = random() % sizeof(b);
        long ib = random() % sizeof(b);

        unsigned char temp = pc[ia];
        pc[ia] = pc[ib];
        pc[ib] = temp;
    }

    // print out the resulting table
    for(int i = 0; i < nBytes; ++i)
    {
        printf("    0x%08x,\n", b[i].u);
    }

    return 0;
}

#endif // PX_NEVER
